# presets.py
"""
Sun preset definitions for the SUN tab.
"""

def get_sun_presets():
    """Return a list of sun presets with all parameters for different maps"""
    return [
        {
            "name": "beltot",
            "r_sunsprite_shader": "sun_beltot",
            "r_sunsprite_size": "62.2501",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.23155",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-9.3504 134.122 0",
        },
        {
            "name": "bergstein",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "143.068",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "496.9",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.36779",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-80 355 0",
        },
        {
            "name": "breakout",
            "r_sunsprite_shader": "sun_silotown_assault",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_toujane",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "84.6081",
            "r_sunflare_max_size": "1309.4",
            "r_sunflare_max_angle": "5.77639",
            "r_sunflare_max_alpha": "0.1",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.20934",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0.21569",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-50 300 0",
        },
        {
            "name": "cityhall",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "109.722",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.23121",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-31 -242 0",
        },
        {
            "name": "credits",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "1",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.23121",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-151.178 189.081 0",
        },
        {
            "name": "crossroads",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "440.451",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "496.9",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.20152",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "340 68 0",
        },
        {
            "name": "decoytown",
            "r_sunsprite_shader": "sun_moon",
            "r_sunsprite_size": "40.1315",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "0",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.20707",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0619999",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-62.6136 200.094 0",
        },
        {
            "name": "decoytrenches",
            "r_sunsprite_shader": "sun_moon",
            "r_sunsprite_size": "40.1315",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "0",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.20707",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0619999",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-62.6136 200.094 0",
        },
        {
            "name": "default",
            "r_sunsprite_shader": "sun",
            "r_sunsprite_size": "16",
            "r_sunflare_shader": "sun_flare",
            "r_sunflare_min_size": "0",
            "r_sunflare_min_angle": "45",
            "r_sunflare_max_size": "700",
            "r_sunflare_max_angle": "2",
            "r_sunflare_max_alpha": "1",
            "r_sunflare_fadein": "0.7",
            "r_sunflare_fadeout": "1",
            "r_sunblind_min_angle": "30",
            "r_sunblind_max_angle": "5",
            "r_sunblind_max_darken": ".5",
            "r_sunblind_fadein": "2.5",
            "r_sunblind_fadeout": "6",
            "r_sunglare_min_angle": "30",
            "r_sunglare_max_angle": "5",
            "r_sunglare_max_lighten": ".3",
            "r_sunglare_fadein": "2.5",
            "r_sunglare_fadeout": "6",
        },
        {
            "name": "demolition",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "214.607",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1437.1",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.31503",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-70 0 0",
        },
        {
            "name": "downtown_assault",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "109.722",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.45622",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.23165",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-24 -127 0",
        },
        {
            "name": "downtown_sniper",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "109.722",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.45622",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.23165",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-37 -27 0",
        },
        {
            "name": "duhoc_assault",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "143.068",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "496.9",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.36779",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-148 19.4 0",
        },
        {
            "name": "duhoc_defend",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "143.068",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "797.2",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.6",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-35 70 0",
        },
        {
            "name": "elalamein",
            "r_sunsprite_shader": "sun_beltot",
            "r_sunsprite_size": "62.2501",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "1.0074",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.23155",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-15.9208 -6.19321 0",
        },
        {
            "name": "eldaba",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "715.6",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1213.5",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.63276",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.39834",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.42271",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-57 315 0",
        },
        {
            "name": "hill400_assault",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "143.068",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "496.9",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.36779",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-45 200 0",
        },
        {
            "name": "hill400_defend",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "143.068",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "496.9",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.36779",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-45 200 0",
        },
        {
            "name": "libya",
            "r_sunsprite_shader": "sun_beltot",
            "r_sunsprite_size": "62.2501",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "1.0074",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.23155",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-15.9208 -6.19321 0",
        },
        {
            "name": "matmata",
            "r_sunsprite_shader": "sun_beltot",
            "r_sunsprite_size": "62.2501",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.23155",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-9.2144 307.886 -16.8552",
        },
        {
            "name": "moscow",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "109.722",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.45622",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.23165",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-38.6856 -53.8224 0",
        },
        {
            "name": "mp_brecourt",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "715.6",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1213.5",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.63276",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.39834",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.42271",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-45 330 0",
        },
        {
            "name": "mp_burgundy",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "715.6",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1213.5",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.63276",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.39834",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.42271",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-45 210 0",
        },
        {
            "name": "mp_carentan",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "715.6",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1213.5",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.63276",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.39834",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.42271",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-45 210 0",
        },
        {
            "name": "mp_dawnville",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "715.6",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1213.5",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.63276",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.39834",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.42271",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-47 149 0",
        },
        {
            "name": "mp_decoy",
            "r_sunsprite_shader": "sun_moon",
            "r_sunsprite_size": "40.1315",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "0",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.20707",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0619999",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-62.6136 200.094 0",
        },
        {
            "name": "mp_harbor",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "109.722",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.45622",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.23165",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-38.6856 -53.8224 0",
        },
        {
            "name": "mp_leningrad",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.23121",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-20 315 0",
        },
        {
            "name": "mp_matmata",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "715.6",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1213.5",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.63276",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.39834",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.42271",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-20 315 0",
        },
        {
            "name": "mp_railyard",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "715.6",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "1213.5",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.63276",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.39834",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.42271",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-40 225 0",
        },
        {
            "name": "mp_rhine",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_toujane",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.20934",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0.21569",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-39.9896 138.12 0",
        },
        {
            "name": "mp_toujane",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_toujane",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.20934",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0.21569",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-45 135 0",
        },
        {
            "name": "newvillers",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "1",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.23121",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-151.178 189.081 0",
        },
        {
            "name": "rhine",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_toujane",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.20934",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0.21569",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-39.9896 138.12 0",
        },
        {
            "name": "silotown_assault",
            "r_sunsprite_shader": "sun_silotown_assault",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_toujane",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "84.6081",
            "r_sunflare_max_size": "1309.4",
            "r_sunflare_max_angle": "5.77639",
            "r_sunflare_max_alpha": "0.36121",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.20934",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0.21569",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-41 212 0",
        },
        {
            "name": "tankhunt",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "594.616",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.23121",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-42 -43 0",
        },
        {
            "name": "toujane",
            "r_sunsprite_shader": "sun_toujane",
            "r_sunsprite_size": "28.8433",
            "r_sunflare_shader": "sun_flare_toujane",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.20934",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0.21569",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-45 135 0",
        },
        {
            "name": "toujane_ride",
            "r_sunsprite_shader": "sun_beltot",
            "r_sunsprite_size": "62.2501",
            "r_sunflare_shader": "sun_flare_beltot",
            "r_sunflare_min_size": "237.8",
            "r_sunflare_min_angle": "40.869",
            "r_sunflare_max_size": "669.9",
            "r_sunflare_max_angle": "2.14669",
            "r_sunflare_max_alpha": "0.62536",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "33.9543",
            "r_sunblind_max_angle": "9.9647",
            "r_sunblind_max_darken": "0.23155",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "10.6101",
            "r_sunglare_max_angle": "48.2526",
            "r_sunglare_max_lighten": "0",
            "r_sunglare_fadein": "2.263",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-9 140 0",
        },
        {
            "name": "trainyard",
            "r_sunsprite_shader": "sun_trainyard",
            "r_sunsprite_size": "109.722",
            "r_sunflare_shader": "sun_flare_trainyard",
            "r_sunflare_min_size": "390.1",
            "r_sunflare_min_angle": "82.3608",
            "r_sunflare_max_size": "889.3",
            "r_sunflare_max_angle": "0",
            "r_sunflare_max_alpha": "0.23121",
            "r_sunflare_fadein": "0.2604",
            "r_sunflare_fadeout": "0.2992",
            "r_sunblind_min_angle": "62.4258",
            "r_sunblind_max_angle": "14.6015",
            "r_sunblind_max_darken": "0.16499",
            "r_sunblind_fadein": "0.5",
            "r_sunblind_fadeout": "1",
            "r_sunglare_min_angle": "20.7108",
            "r_sunglare_max_angle": "5.7933",
            "r_sunglare_max_lighten": "0.0930199",
            "r_sunglare_fadein": "0.7758",
            "r_sunglare_fadeout": "3",
            "r_sun_fx_position": "-70 172 0",
        },
    ]



def get_sun_preset_names():
    """Returns just the names for the combobox."""
    return [p["name"] for p in get_sun_presets()]


def get_sun_preset_by_name(name):
    """Returns the full preset dict by name, or None if not found."""
    for preset in get_sun_presets():
        if preset["name"] == name:
            return preset
    return None