# ui/tab_model_viewer.py
# NEW FILE – create this in the ui/ folder

import tkinter as tk
from tkinter import ttk, messagebox
from pathlib import Path
from PIL import Image, ImageTk
import urllib.request
import zipfile
import shutil
import tempfile


MODELS = [
    "american_radio.png",
    "artillery_british_6pndr.png",
    "awning_2-5x11.png",
    "awning_2x4-5_1.png",
    "awning_2x4-5_2.png",
    "awning_2x4-5_3.png",
    "awning_2x4_1.png",
    "awning_2x4_2.png",
    "awning_2x4_3.png",
    "awning_2x4_4.png",
    "awning_2x4_5.png",
    "awning_2x5_1.png",
    "awning_2x5_2.png",
    "awning_3x4_1.png",
    "awning_3x4_2.png",
    "awning_desert_market_large.png",
    "awning_desert_market_large2.png",
    "awning_desert_market_medium1.png",
    "awning_desert_market_medium2.png",
    "awning_desert_market_small.png",
    "awning_desert_wood1.png",
    "awning_desert_wood2.png",
    "awning_desert_wood3.png",
    "awning_desert_wood4.png",
    "awning_desert_wood_large1.png",
    "awning_desert_wood_large2.png",
    "awning_desert_wood_large3.png",
    "awning_desert_wood_large4.png",
    "awning_desert_wood_long.png",
    "backdrop_british_destroyer.png",
    "backdrop_newvillers_card.png",
    "backdrop_newvillers_trees.png",
    "backdrop_rhine_card.png",
    "backdrop_silotown_trees.png",
    "backdrop_toujane_card.png",
    "backdrop_toujane_frnthill.png",
    "backdrop_toujane_frntmntn.png",
    "british_afrca_mac_radio_back.png",
    "british_afrca_mac_radio_hand.png",
    "brush_desertgreenfanshrub.png",
    "brush_desertgreenfanshrub_tankdrive1.png",
    "brush_desertgreenfanshrub_tankdrive2.png",
    "brush_desertgreenfanshrub_tankdrive3.png",
    "brush_desertshrubbrownmid.png",
    "brush_desertshrubbrownshort.png",
    "brush_desertshrubbrowntall.png",
    "brush_desertshrubgraymid.png",
    "brush_desertshrubgrayshort.png",
    "brush_desertshrubgraytall.png",
    "brush_desertshrubgraytall_tankdrive1.png",
    "brush_desertshrubgraytall_tankdrive2.png",
    "brush_desertshrubgraytall_tankdrive3.png",
    "brush_desertshrubgroup01.png",
    "brush_desertshrubgroup01_tankdrive1.png",
    "brush_desertshrubgroup01_tankdrive2.png",
    "brush_desertshrubgroup01_tankdrive3.png",
    "brush_desertspikeyshrub.png",
    "brush_egypt_desert_1.png",
    "brush_egypt_desert_2.png",
    "brush_egypt_desert_2_tankdrive1.png",
    "brush_egypt_desert_2_tankdrive2.png",
    "brush_egypt_desert_2_tankdrive3.png",
    "brush_grassflowerplants_squareclump.png",
    "brush_grassflowerplants_triangularclump.png",
    "brush_grasslowline.png",
    "brush_newgrasstuft_shortwide.png",
    "brush_newgrasstuft_tallnarrow.png",
    "brush_newgrass_squareclump.png",
    "brush_newgrass_squareclumpshort.png",
    "brush_newgrass_triangularclump.png",
    "brush_newgrass_triangularclumpshort.png",
    "brush_shortnewgrass_squareclump.png",
    "brush_shortnewgrass_squareclumpshort.png",
    "brush_shortnewgrass_triangularclump.png",
    "brush_shortnewgrass_triangularclumpshort.png",
    "brush_snowbushweed01.png",
    "brush_snowbushweed02.png",
    "brush_toujanebigbushy.png",
    "bunker01.png",
    "bunker02.png",
    "bunker03.png",
    "bunker04.png",
    "bunker_ceiling_light_off.png",
    "bunker_ceiling_light_on.png",
    "bunker_pipe_elbow.png",
    "bunker_pipe_length.png",
    "bunker_pipe_short.png",
    "bunker_pipe_tconnection.png",
    "bunker_pipe_xconnection.png",
    "bunker_wall_light_off.png",
    "bunker_wall_light_on.png",
    "caen_barbedwire_1.png",
    "caen_barbedwire_2.png",
    "caen_barbedwire_3.png",
    "caen_barbedwire_4.png",
    "caen_barbedwire_5.png",
    "caen_barbedwire_5_noaicol.png",
    "caen_barbedwire_6.png",
    "caen_barbedwire_7.png",
    "caen_barbedwire_8.png",
    "caen_barbedwire_9.png",
    "caen_bush_full_01.png",
    "caen_churchpew_01.png",
    "caen_fence_1.png",
    "caen_fence_2.png",
    "caen_fence_3.png",
    "caen_fence_gate_1.png",
    "caen_fence_post_1.png",
    "caen_grasstuft_5.png",
    "caen_grasstuft_group_01.png",
    "caen_hedgewallgroup_flip_1.png",
    "caen_hedgewall_endcap.png",
    "caen_hedge_wall_1.png",
    "caen_hedge_wall_2.png",
    "caen_hedge_wall_3.png",
    "caen_hedge_wall_group_1.png",
    "caen_spikeybush_01.png",
    "caen_weeds_01.png",
    "caen_windowpulleyhook.png",
    "caen_window_brown_broken_1.png",
    "caen_window_brown_broken_2.png",
    "caen_window_brown_broken_3.png",
    "caen_window_brown_clean_1.png",
    "caen_window_brown_clean_2.png",
    "caen_window_brown_clean_3.png",
    "caen_window_white_broken_1.png",
    "caen_window_white_broken_2.png",
    "caen_window_white_broken_3.png",
    "caen_window_white_clean_1.png",
    "caen_window_white_clean_2.png",
    "caen_window_white_clean_3.png",
    "character_british_afrca_body.png",
    "character_british_afrca_body_low.png",
    "character_british_afrca_mac_body.png",
    "character_british_afrca_mac_radio.png",
    "character_british_afrca_mcgregor_low.png",
    "character_british_afrca_shortsleeve_body.png",
    "character_british_africa_price.png",
    "character_british_duhoc_driver.png",
    "character_british_normandy_a.png",
    "character_british_normandy_b.png",
    "character_british_normandy_c.png",
    "character_british_normandy_mac_body.png",
    "character_british_normandy_price.png",
    "character_german_afrca_body.png",
    "character_german_afrca_casualbody.png",
    "character_german_camo_fat.png",
    "character_german_josh_preview.png",
    "character_german_normandy_coat_dark.png",
    "character_german_normandy_fat.png",
    "character_german_normandy_fat_injured.png",
    "character_german_normandy_officer.png",
    "character_german_normandy_thin.png",
    "character_german_normandy_thin_injured.png",
    "character_german_winter_hooded.png",
    "character_german_winter_light.png",
    "character_german_winter_masked_dark.png",
    "character_german_winter_mg42_low.png",
    "character_russian_diana_medic.png",
    "character_russian_padded_a.png",
    "character_russian_padded_b.png",
    "character_russian_trench_a.png",
    "character_russian_trench_b.png",
    "character_russian_trench_c.png",
    "character_russian_trench_d.png",
    "character_russian_trench_popov.png",
    "character_russian_winter_body.png",
    "character_us_ranger_cpl_a.png",
    "character_us_ranger_lt_coffey.png",
    "character_us_ranger_medic_wells.png",
    "character_us_ranger_pvt_a.png",
    "character_us_ranger_pvt_a_low.png",
    "character_us_ranger_pvt_a_wounded.png",
    "character_us_ranger_pvt_b.png",
    "character_us_ranger_pvt_braeburn.png",
    "character_us_ranger_pvt_b_low.png",
    "character_us_ranger_pvt_b_wounded.png",
    "character_us_ranger_pvt_c.png",
    "character_us_ranger_pvt_c_low.png",
    "character_us_ranger_pvt_d.png",
    "character_us_ranger_pvt_d_low.png",
    "character_us_ranger_pvt_mccloskey.png",
    "character_us_ranger_radio.png",
    "character_us_ranger_sgt_randall.png",
    "character_us_wet_ranger_lt_coffey.png",
    "character_us_wet_ranger_medic_wells.png",
    "character_us_wet_ranger_pvt_a.png",
    "character_us_wet_ranger_pvt_a_low.png",
    "character_us_wet_ranger_pvt_a_wounded.png",
    "character_us_wet_ranger_pvt_b.png",
    "character_us_wet_ranger_pvt_braeburn.png",
    "character_us_wet_ranger_pvt_b_low.png",
    "character_us_wet_ranger_pvt_b_wounded.png",
    "character_us_wet_ranger_pvt_c.png",
    "character_us_wet_ranger_pvt_c_low.png",
    "character_us_wet_ranger_pvt_d.png",
    "character_us_wet_ranger_pvt_d_low.png",
    "character_us_wet_ranger_pvt_mccloskey.png",
    "character_us_wet_ranger_radio.png",
    "character_us_wet_ranger_sgt_a.png",
    "character_us_wet_ranger_sgt_randall.png",
    "civiliancar_damaged_blue.png",
    "civiliancar_intact_blue.png",
    "cliff01.png",
    "cliff02.png",
    "cliff03.png",
    "cliff04.png",
    "cliff05.png",
    "cliff06.png",
    "cliff07.png",
    "cow_dead_1.png",
    "cow_dead_2.png",
    "cow_dead_3.png",
    "crate01.png",
    "crate01_snow.png",
    "crate02.png",
    "crate02_snow.png",
    "defaultactor.png",
    "defaultvehicle.png",
    "defaultweapon.png",
    "default_static_model.png",
    "dome_01.png",
    "dome_02.png",
    "dome_03.png",
    "dome_04.png",
    "dome_05.png",
    "dome_06.png",
    "dome_07.png",
    "dome_08.png",
    "door_barn.png",
    "door_barn_credit.png",
    "duhoc_climb_rope_rig_test.png",
    "duhoc_drones_rig.png",
    "duhoc_halfrock1.png",
    "duhoc_halfrock2.png",
    "duhoc_halfrock3.png",
    "duhoc_halfrock4.png",
    "duhoc_halfrock5.png",
    "duhoc_player_viewcam_joints.png",
    "duhoc_rock_a.png",
    "duhoc_rock_b.png",
    "duhoc_rock_c.png",
    "duhoc_rock_d.png",
    "duhoc_rope_climb_cliff_player_rig.png",
    "duhoc_rope_climb_cliff_rig.png",
    "duhoc_rope_rig_test.png",
    "duhoc_vehicle_drones.png",
    "egypt_bunker_tanker.png",
    "egypt_bunker_window_shutter.png",
    "egypt_prop_buildingpiece01.png",
    "egypt_prop_buildingpiece02.png",
    "egypt_prop_buildingpiece03.png",
    "egypt_prop_buildingpiece04.png",
    "egypt_prop_cloth1.png",
    "egypt_prop_cloth2.png",
    "egypt_prop_cloth3.png",
    "egypt_prop_vase1.png",
    "egypt_prop_vase1_interior.png",
    "egypt_prop_vase2.png",
    "egypt_prop_vase2_interior.png",
    "egypt_prop_vase3.png",
    "egypt_prop_vase3_interior.png",
    "egypt_prop_vase4.png",
    "egypt_prop_vase4_interior.png",
    "egypt_prop_vase5.png",
    "egypt_prop_vase5_interior.png",
    "egypt_prop_vase6.png",
    "egypt_prop_vase6_interior.png",
    "egypt_prop_vase_br1.png",
    "egypt_prop_vase_br1_interior.png",
    "egypt_prop_vase_br2.png",
    "egypt_prop_vase_br2_interior.png",
    "egypt_prop_vase_br3.png",
    "egypt_prop_vase_br3_interior.png",
    "egypt_prop_vase_br4.png",
    "egypt_prop_vase_br4_interior.png",
    "egypt_prop_vase_br5.png",
    "egypt_prop_vase_br5_interior.png",
    "egypt_prop_vase_br6.png",
    "egypt_prop_vase_br6_interior.png",
    "egypt_prop_vase_br7.png",
    "egypt_prop_vase_br7_interior.png",
    "egypt_prop_well1.png",
    "egypt_prop_well2.png",
    "egypt_prop_woodrail.png",
    "elalamein_drones_joints.png",
    "eldaba_plane_rig.png",
    "eldaba_tower_explode.png",
    "furniture_armchair.png",
    "furniture_armchair_d.png",
    "furniture_armoire.png",
    "furniture_armoire_d.png",
    "furniture_bathtub.png",
    "furniture_bathtub_d.png",
    "furniture_bathtub_obj.png",
    "furniture_bed.png",
    "furniture_bedhandle_bunker.png",
    "furniture_bedmattress1.png",
    "furniture_bedmattress2.png",
    "furniture_bedmattress_bunker.png",
    "furniture_bedmetalpiece_bunker.png",
    "furniture_bed_bunker.png",
    "furniture_bed_bunker1.png",
    "furniture_bed_bunker2.png",
    "furniture_bed_d.png",
    "furniture_bookshelves1.png",
    "furniture_bookshelves1_d.png",
    "furniture_bookshelvestall.png",
    "furniture_bookshelveswide.png",
    "furniture_brokentableleg.png",
    "furniture_cabinet.png",
    "furniture_canopybed.png",
    "furniture_desk.png",
    "furniture_desk_d_a.png",
    "furniture_desk_d_b.png",
    "furniture_desk_d_c.png",
    "furniture_desk_d_d.png",
    "furniture_desk_d_drawer.png",
    "furniture_dirtysink.png",
    "furniture_dresser.png",
    "furniture_dresser_d.png",
    "furniture_duhoc_armchair.png",
    "furniture_duhoc_armchair_dirty.png",
    "furniture_duhoc_armchair_dirty_blue.png",
    "furniture_duhoc_armchair_dirty_red.png",
    "furniture_duhoc_bunker_seat.png",
    "furniture_duhoc_bunker_table.png",
    "furniture_duhoc_chair.png",
    "furniture_duhoc_chair_dirty1.png",
    "furniture_duhoc_chair_dirty2.png",
    "furniture_duhoc_chair_dirty3.png",
    "furniture_duhoc_clock.png",
    "furniture_duhoc_couch.png",
    "furniture_duhoc_couch_cushion1.png",
    "furniture_duhoc_couch_cushion1_d1.png",
    "furniture_duhoc_couch_cushion1_d2.png",
    "furniture_duhoc_couch_cushion1_d3.png",
    "furniture_duhoc_couch_cushion2.png",
    "furniture_duhoc_couch_cushion2_d1.png",
    "furniture_duhoc_couch_cushion2_d2.png",
    "furniture_duhoc_couch_cushion2_d3.png",
    "furniture_duhoc_couch_dirty1.png",
    "furniture_duhoc_couch_dirty2.png",
    "furniture_duhoc_couch_dirty3.png",
    "furniture_duhoc_table.png",
    "furniture_file_cabinet_drawer.png",
    "furniture_file_cabinet_long_a.png",
    "furniture_file_cabinet_med_a.png",
    "furniture_file_cabinet_short_a.png",
    "furniture_frenchbathcurtainrail.png",
    "furniture_frenchbathfaucet.png",
    "furniture_frenchbathshowerhead.png",
    "furniture_frenchbathtub1.png",
    "furniture_frenchbathtub2.png",
    "furniture_frenchbathtubmetal.png",
    "furniture_frenchbathtubporcelain.png",
    "furniture_frenchtoilet1.png",
    "furniture_frenchtoilet2.png",
    "furniture_frenchtoiletbowl.png",
    "furniture_frenchtoiletseatcover.png",
    "furniture_frenchtoilet_tank.png",
    "furniture_french_sink.png",
    "furniture_french_sink1.png",
    "furniture_french_sink2.png",
    "furniture_french_sinkpedestal.png",
    "furniture_french_sinkpipe.png",
    "furniture_french_sinkstand.png",
    "furniture_fullbed.png",
    "furniture_grandfatherclocktall.png",
    "furniture_longdiningtable.png",
    "furniture_longdiningtable_d.png",
    "furniture_northafrica_armoire_short.png",
    "furniture_northafrica_armoire_tall.png",
    "furniture_northafrica_coffeetable.png",
    "furniture_northafrica_egyptianchair.png",
    "furniture_northafrica_halftable.png",
    "furniture_northafrica_longtable.png",
    "furniture_northafrica_woodchair.png",
    "furniture_ovaldiningtable.png",
    "furniture_piano.png",
    "furniture_piano_d.png",
    "furniture_plainchair.png",
    "furniture_plainchair_d.png",
    "furniture_plainchair_mo.png",
    "furniture_plainchair_shardback.png",
    "furniture_plainchair_shardleg.png",
    "furniture_plainchair_shardrail.png",
    "furniture_plainchair_shardseat.png",
    "furniture_rolltopdesk.png",
    "furniture_rolltopdesk_d.png",
    "furniture_sidetable1.png",
    "furniture_sidetable1_d.png",
    "furniture_smallcoffeetable.png",
    "furniture_smallfoldingtable.png",
    "furniture_tableclock1.png",
    "furniture_tableclock2.png",
    "furniture_toilet.png",
    "furniture_utilitychair1.png",
    "furniture_utilitychair2.png",
    "furniture_victoriancouch.png",
    "furniture_victoriancouch_d.png",
    "furniture_walltable1.png",
    "furniture_walltable1_d.png",
    "furniture_walltable2.png",
    "furniture_walltable2_d.png",
    "fx.png",
    "german_artillery_155gpf.png",
    "german_artillery_155gpf_d.png",
    "german_artillery_flak88.png",
    "german_artillery_flak88_aa_d_static.png",
    "german_artillery_flak88_aa_nm_d_static.png",
    "german_artillery_flak88_aa_nm_static.png",
    "german_artillery_flak88_aa_static.png",
    "german_artillery_flak88_destroy.png",
    "german_artillery_flak88_d_static.png",
    "german_artillery_flak88_nm.png",
    "german_artillery_flak88_nm_destroy.png",
    "german_artillery_flak88_static.png",
    "german_artillery_flakveirling.png",
    "german_artillery_flakveirling_d.png",
    "german_artillery_flakveirling_viewmodel.png",
    "german_grenade_bag.png",
    "grasstuftgroup_bigclump_test.png",
    "grasstuftgroup_row_test.png",
    "grasstuftgroup_test.png",
    "grasstuft_test.png",
    "gully_basementwall_rig.png",
    "gully_bridge01.png",
    "gully_bridge01_middle.png",
    "gully_bridge02.png",
    "gully_bridge_concrete01.png",
    "gully_bridge_concrete02.png",
    "gully_bridge_concrete03.png",
    "gully_bridge_debris_lg01.png",
    "gully_bridge_debris_lg02.png",
    "gully_bridge_debris_lg03.png",
    "gully_bridge_debris_sm01.png",
    "gully_bridge_debris_sm02.png",
    "gully_bridge_debris_sm03.png",
    "haycart.png",
    "haycart_destroyed.png",
    "head_british_boon.png",
    "head_british_chance.png",
    "head_british_chance_low.png",
    "head_british_harry.png",
    "head_british_joel.png",
    "head_british_joel_driver.png",
    "head_british_macgregor.png",
    "head_british_paul.png",
    "head_british_paul_low.png",
    "head_british_price.png",
    "head_british_wellington.png",
    "head_german_afrca_christoph.png",
    "head_german_afrca_eric.png",
    "head_german_afrca_josh.png",
    "head_german_africa_mask.png",
    "head_german_normandy_christoph.png",
    "head_german_normandy_dan.png",
    "head_german_normandy_emilio.png",
    "head_german_normandy_eric.png",
    "head_german_normandy_ericp.png",
    "head_german_normandy_josh.png",
    "head_german_winter_ericp.png",
    "head_german_winter_jon.png",
    "head_german_winter_jon_low.png",
    "head_russian_winter_alex.png",
    "head_russian_winter_dan.png",
    "head_russian_winter_datien.png",
    "head_russian_winter_jesse.png",
    "head_russian_winter_jon.png",
    "head_russian_winter_popov.png",
    "head_russian_winter_volsky.png",
    "head_us_ranger_braeburn.png",
    "head_us_ranger_david.png",
    "head_us_ranger_david_low.png",
    "head_us_ranger_frank.png",
    "head_us_ranger_frank_low.png",
    "head_us_ranger_grant.png",
    "head_us_ranger_harry.png",
    "head_us_ranger_harry_low.png",
    "head_us_ranger_medic_wells.png",
    "head_us_ranger_mo.png",
    "head_us_ranger_mo_low.png",
    "head_us_ranger_preston.png",
    "head_us_ranger_randall.png",
    "head_us_ranger_wolf.png",
    "head_us_ranger_wolf_low.png",
    "health_large.png",
    "health_medium.png",
    "health_small.png",
    "helmet_british_afrca.png",
    "helmet_british_afrca_low.png",
    "helmet_british_africa_mac.png",
    "helmet_british_joel_driver.png",
    "helmet_british_normandy.png",
    "helmet_british_normandy_a.png",
    "helmet_british_normandy_b.png",
    "helmet_british_normandy_mac.png",
    "helmet_german_africa.png",
    "helmet_german_camo_emilio.png",
    "helmet_german_casual_africa.png",
    "helmet_german_normandy.png",
    "helmet_german_normandy_coat_dark.png",
    "helmet_german_normandy_emilio.png",
    "helmet_german_normandy_officer_hat.png",
    "helmet_german_winter_dark.png",
    "helmet_german_winter_jon.png",
    "helmet_russian_padded_a.png",
    "helmet_russian_padded_b.png",
    "helmet_russian_trench_a_hat.png",
    "helmet_russian_trench_b_hat.png",
    "helmet_russian_trench_c_hat.png",
    "helmet_russian_trench_d_hat.png",
    "helmet_russian_trench_popov_hat.png",
    "helmet_us_ranger_braeburn.png",
    "helmet_us_ranger_generic.png",
    "helmet_us_ranger_generic_low.png",
    "helmet_us_ranger_medic_wells.png",
    "helmet_us_ranger_mo.png",
    "helmet_us_ranger_randall.png",
    "helmet_us_ranger_static.png",
    "helmet_us_wet_ranger_braeburn.png",
    "helmet_us_wet_ranger_generic.png",
    "helmet_us_wet_ranger_generic_low.png",
    "helmet_us_wet_ranger_medic_wells.png",
    "helmet_us_wet_ranger_mo.png",
    "helmet_us_wet_ranger_randall.png",
    "helmet_us_wet_ranger_static.png",
    "hill400_barrel_black.png",
    "hill400_barrel_green.png",
    "hill400_crate.png",
    "hill400_dragonstooth.png",
    "hill400_dragonstooth_d.png",
    "hill400_hedgehog.png",
    "hill400_rock_a.png",
    "hill400_rock_b.png",
    "hill400_rock_c.png",
    "hill400_rock_d.png",
    "hill400_sandbag_cornersection.png",
    "hill400_sandbag_curvedsection.png",
    "hill400_sandbag_endsection_left.png",
    "hill400_sandbag_endsection_right.png",
    "hill400_sandbag_longsection.png",
    "hill400_sandbag_shortsection.png",
    "hill400_sandbag_single_bent.png",
    "hill400_sandbag_single_flat.png",
    "horse_dead_1.png",
    "horse_dead_2.png",
    "light_candelabre_off.png",
    "light_chandalier_off.png",
    "light_flaksheinwerfer_on.png",
    "light_lampdesk_off.png",
    "light_lampornate_off.png",
    "light_lampornate_on.png",
    "light_lampplainmetalbase_off.png",
    "light_lampplain_on.png",
    "light_lamptiffany_on.png",
    "light_lantern_off.png",
    "light_lantern_on.png",
    "light_signallight_off.png",
    "light_walllightcrystal_off.png",
    "light_walllightcrystal_on.png",
    "light_walllightornate_off.png",
    "light_walllight_off.png",
    "light_walllight_on.png",
    "mannequin.png",
    "mannequin_arm_l.png",
    "mannequin_arm_r.png",
    "mannequin_dressform.png",
    "mannequin_dressform_coat.png",
    "mannequin_dressform_coat_obj.png",
    "mannequin_head.png",
    "military_bunker_electrical_box.png",
    "military_bunker_vent.png",
    "military_dragonstooth.png",
    "military_dragonstooth_d.png",
    "military_dragonstooth_egypt.png",
    "military_dragonstooth_egypt_d.png",
    "military_dragonstooth_snow.png",
    "military_dragonstooth_snow_d.png",
    "military_dragonstooth_wet.png",
    "military_dragonstooth_wet_d.png",
    "military_flak88_box.png",
    "military_flak88_boxlid.png",
    "military_flak88_box_empty.png",
    "military_flak88_box_open.png",
    "military_flak88_emptyshell.png",
    "military_flak88_shell.png",
    "military_flak88_tube.png",
    "military_german_fieldradio_green.png",
    "military_german_fieldradio_green_d.png",
    "military_german_fieldradio_green_nonsolid.png",
    "military_german_fieldradio_green_obj.png",
    "military_german_fieldradio_grey.png",
    "military_german_fieldradio_grey_d.png",
    "military_german_fieldradio_grey_nonsolid.png",
    "military_german_fieldradio_grey_obj.png",
    "military_german_fieldradio_tan.png",
    "military_german_fieldradio_tan_d.png",
    "military_german_fieldradio_tan_nonsolid.png",
    "military_german_fieldradio_tan_obj.png",
    "military_german_headset.png",
    "military_german_headset_obj.png",
    "military_german_microphone.png",
    "military_german_microphone_obj.png",
    "military_german_radio1_green.png",
    "military_german_radio1_green_d.png",
    "military_german_radio1_green_obj.png",
    "military_german_radio1_grey.png",
    "military_german_radio1_grey_d.png",
    "military_german_radio1_grey_obj.png",
    "military_german_radio1_tan.png",
    "military_german_radio1_tan_d.png",
    "military_german_radio1_tan_obj.png",
    "military_german_radio2_green.png",
    "military_german_radio2_green_d.png",
    "military_german_radio2_green_obj.png",
    "military_german_radio2_grey.png",
    "military_german_radio2_grey_d.png",
    "military_german_radio2_grey_obj.png",
    "military_german_radio2_tan.png",
    "military_german_radio2_tan_d.png",
    "military_german_radio2_tan_obj.png",
    "military_hedgehog.png",
    "military_hedgehog_small.png",
    "military_panzerfaust.png",
    "military_panzerfaust_box_empty.png",
    "military_panzerfaust_box_full.png",
    "military_sandbag_cornersection.png",
    "military_sandbag_curvedsection.png",
    "military_sandbag_desert_cornersection.png",
    "military_sandbag_desert_curvedsection.png",
    "military_sandbag_desert_endsection_left.png",
    "military_sandbag_desert_endsection_right.png",
    "military_sandbag_desert_expld_shortsection.png",
    "military_sandbag_desert_exploded_left.png",
    "military_sandbag_desert_exploded_right.png",
    "military_sandbag_desert_exploded_single.png",
    "military_sandbag_desert_longsection.png",
    "military_sandbag_desert_shortsection.png",
    "military_sandbag_desert_single_bent.png",
    "military_sandbag_desert_single_flat.png",
    "military_sandbag_endsection_left.png",
    "military_sandbag_endsection_right.png",
    "military_sandbag_group_expld_shortsection.png",
    "military_sandbag_group_exploded_left.png",
    "military_sandbag_group_exploded_right.png",
    "military_sandbag_longsection.png",
    "military_sandbag_shortsection.png",
    "military_sandbag_single_bent.png",
    "military_sandbag_single_exploded_01.png",
    "military_sandbag_single_exploded_02.png",
    "military_sandbag_single_flat.png",
    "military_sandbag_snow_cornersection.png",
    "military_sandbag_snow_curvedsection.png",
    "military_sandbag_snow_endsection_left.png",
    "military_sandbag_snow_endsection_right.png",
    "military_sandbag_snow_longsection.png",
    "military_sandbag_snow_long_no_ai_col.png",
    "military_sandbag_snow_shortsection.png",
    "military_sandbag_snow_single_bent.png",
    "military_sandbag_snow_single_flat.png",
    "military_sandbag_wet_cornersection.png",
    "military_sandbag_wet_curvedsection.png",
    "military_sandbag_wet_endsection_left.png",
    "military_sandbag_wet_endsection_right.png",
    "military_sandbag_wet_longsection.png",
    "military_sandbag_wet_shortsection.png",
    "military_sandbag_wet_single_bent.png",
    "military_sandbag_wet_single_flat.png",
    "military_tntbomb.png",
    "military_tntbomb_obj.png",
    "moscow_boards_1a.png",
    "moscow_boards_1b.png",
    "moscow_boards_2a.png",
    "moscow_boards_2b.png",
    "moscow_brick_grey.png",
    "moscow_brick_red.png",
    "moscow_doorframe1.png",
    "moscow_doorframe1_obj.png",
    "moscow_gun_positioin_rig.png",
    "moscow_window1.png",
    "moscow_window1_obj.png",
    "moscow_window2.png",
    "mp_tntbomb.png",
    "mp_tntbomb_obj.png",
    "pallet01.png",
    "pallet02.png",
    "playerbody_american_normandy01.png",
    "playerbody_american_normandy02.png",
    "playerbody_american_normandy03.png",
    "playerbody_american_normandy04.png",
    "playerbody_american_normandy05.png",
    "playerbody_american_normandy06.png",
    "playerbody_american_normandy07.png",
    "playerbody_american_normandy08.png",
    "playerbody_american_normandy09.png",
    "playerbody_british_africa01.png",
    "playerbody_british_africa02.png",
    "playerbody_british_africa03.png",
    "playerbody_british_africa04.png",
    "playerbody_british_normandy01.png",
    "playerbody_british_normandy02.png",
    "playerbody_british_normandy03.png",
    "playerbody_british_normandy04.png",
    "playerbody_british_normandy05.png",
    "playerbody_default.png",
    "playerbody_german_africa01.png",
    "playerbody_german_normandy01.png",
    "playerbody_german_winterdark.png",
    "playerbody_german_winterdark_masked.png",
    "playerbody_german_winterlight.png",
    "playerbody_german_winterlight_hooded.png",
    "playerbody_russian_coat01.png",
    "playerbody_russian_coat02.png",
    "playerbody_russian_coat03.png",
    "playerbody_russian_coat04.png",
    "playerbody_russian_coat05.png",
    "playerbody_russian_padded01.png",
    "playerbody_russian_padded02.png",
    "playerhead_default.png",
    "pointeground.png",
    "powerpole01.png",
    "powerpole02.png",
    "powerpole_d01.png",
    "powerpole_d02.png",
    "powerpole_d03.png",
    "projectile_britishgrenade.png",
    "projectile_germangrenade.png",
    "projectile_mk2fraggrenade.png",
    "projectile_russiangrenade.png",
    "projectile_us_smoke_grenade.png",
    "prop_barrel_benzin.png",
    "prop_barrel_benzin_snow.png",
    "prop_barrel_benzin_wet.png",
    "prop_barrel_black.png",
    "prop_barrel_black_snow.png",
    "prop_barrel_black_wet.png",
    "prop_barrel_green.png",
    "prop_barrel_green_snow.png",
    "prop_barrel_green_snowside.png",
    "prop_barrel_green_wet.png",
    "prop_barrel_piece.png",
    "prop_barrel_piece2.png",
    "prop_barrel_shard1.png",
    "prop_barrel_shard2.png",
    "prop_barrel_shard3.png",
    "prop_barrel_shard4.png",
    "prop_barrel_shard5.png",
    "prop_barrel_silver.png",
    "prop_barrel_silver_snow.png",
    "prop_barrel_silver_wet.png",
    "prop_barrel_tan.png",
    "prop_barrel_tan_wet.png",
    "prop_barrel_white.png",
    "prop_barrel_white_snow.png",
    "prop_bear.png",
    "prop_bear_detail.png",
    "prop_bear_detail_sitting.png",
    "prop_bear_obj.png",
    "prop_bench_d.png",
    "prop_bike.png",
    "prop_bike_destroyed.png",
    "prop_book1.png",
    "prop_book2.png",
    "prop_book3.png",
    "prop_bunkerlightswitch.png",
    "prop_bunkerlocker_double.png",
    "prop_bunkerlocker_open.png",
    "prop_bunkerlocker_single.png",
    "prop_bunker_air_filter.png",
    "prop_bunker_phone.png",
    "prop_bunker_stove.png",
    "prop_chickencoop.png",
    "prop_churchdome_destroyed.png",
    "prop_churchdome_intact.png",
    "prop_crate_dak1.png",
    "prop_crate_dak1_russian.png",
    "prop_crate_dak2.png",
    "prop_crate_dak2_russian.png",
    "prop_crate_dak3.png",
    "prop_crate_dak3_russian.png",
    "prop_crate_dak4.png",
    "prop_crate_dak4_russian.png",
    "prop_crate_dak5.png",
    "prop_crate_dak5_russian.png",
    "prop_crate_dak6.png",
    "prop_crate_dak6_russian.png",
    "prop_crate_dak7.png",
    "prop_crate_dak7_russian.png",
    "prop_crate_dak8.png",
    "prop_crate_dak8_russian.png",
    "prop_crate_dak9.png",
    "prop_crate_dak9_russian.png",
    "prop_crate_dak_shard.png",
    "prop_crate_largeshipping1.png",
    "prop_crate_largeshipping_lid.png",
    "prop_crate_largeshipping_open1.png",
    "prop_crate_smallshipping1.png",
    "prop_crate_smallshipping_open1.png",
    "prop_crate_smallshipping_open2.png",
    "prop_crate_smallshipping_open3.png",
    "prop_crate_wehrmacht1.png",
    "prop_crate_wehrmacht1a.png",
    "prop_crate_wehrmacht1a_wet.png",
    "prop_crate_wehrmacht1_wet.png",
    "prop_crate_wehrmacht2.png",
    "prop_crate_wehrmacht2a.png",
    "prop_crate_wehrmacht2a_wet.png",
    "prop_crate_wehrmacht2_wet.png",
    "prop_crate_wehrmacht3.png",
    "prop_crate_wehrmacht3a.png",
    "prop_crate_wehrmacht3a_wet.png",
    "prop_crate_wehrmacht3_wet.png",
    "prop_crate_wehrmacht4.png",
    "prop_crate_wehrmacht4a.png",
    "prop_crate_wehrmacht4a_wet.png",
    "prop_crate_wehrmacht4_wet.png",
    "prop_crate_wehrmacht5.png",
    "prop_crate_wehrmacht5a.png",
    "prop_crate_wehrmacht5a_wet.png",
    "prop_crate_wehrmacht5_wet.png",
    "prop_crate_wehrmacht6.png",
    "prop_crate_wehrmacht6a.png",
    "prop_crate_wehrmacht6a_wet.png",
    "prop_crate_wehrmacht6_wet.png",
    "prop_crate_wehrmacht7.png",
    "prop_crate_wehrmacht7a.png",
    "prop_crate_wehrmacht7a_wet.png",
    "prop_crate_wehrmacht7_wet.png",
    "prop_crate_wehrmacht8.png",
    "prop_crate_wehrmacht8a.png",
    "prop_crate_wehrmacht8a_wet.png",
    "prop_crate_wehrmacht8_wet.png",
    "prop_crate_wehrmacht9.png",
    "prop_crate_wehrmacht9a.png",
    "prop_crate_wehrmacht9a_wet.png",
    "prop_crate_wehrmacht9_wet.png",
    "prop_crypt1.png",
    "prop_crypt2.png",
    "prop_dept_sign.png",
    "prop_destroyedcratebox.png",
    "prop_destroyedcratecorner01.png",
    "prop_destroyedcratecorner02.png",
    "prop_destroyedcrateplanks01.png",
    "prop_destroyedcrateplanks02.png",
    "prop_destroyedcrateside.png",
    "prop_diningplate_brokenfloral1.png",
    "prop_diningplate_brokenfloral2.png",
    "prop_diningplate_brokenfloral3.png",
    "prop_diningplate_brokenfloral4.png",
    "prop_diningplate_brokenplain1.png",
    "prop_diningplate_brokenplain2.png",
    "prop_diningplate_brokenplain3.png",
    "prop_diningplate_brokenplain4.png",
    "prop_diningplate_ovalfloral.png",
    "prop_diningplate_ovalplain.png",
    "prop_diningplate_ovalstack.png",
    "prop_diningplate_roundfloral.png",
    "prop_diningplate_roundplain.png",
    "prop_diningplate_roundstack.png",
    "prop_doghouse1.png",
    "prop_doghouse2.png",
    "prop_doorknob.png",
    "prop_doorknob1.png",
    "prop_door_metal_bunker.png",
    "prop_door_metal_bunker_damaged.png",
    "prop_door_metal_hatch.png",
    "prop_door_metal_hatch_hinge.png",
    "prop_door_wood.png",
    "prop_door_wood_arched.png",
    "prop_door_wood_arched_damaged.png",
    "prop_door_wood_arched_d_static.png",
    "prop_door_wood_d.png",
    "prop_firebarrel.png",
    "prop_flag_american.png",
    "prop_flag_american_carry.png",
    "prop_flag_base.png",
    "prop_flag_british.png",
    "prop_flag_british_carry.png",
    "prop_flag_german.png",
    "prop_flag_german_carry.png",
    "prop_flag_russian.png",
    "prop_flag_russian_carry.png",
    "prop_flak88_nm_piece0.png",
    "prop_flak88_nm_piece1.png",
    "prop_flak88_nm_piece2.png",
    "prop_flak88_nm_piece3.png",
    "prop_flak88_piece0.png",
    "prop_flak88_piece1.png",
    "prop_flak88_piece2.png",
    "prop_flak88_piece3.png",
    "prop_geraniums_1.png",
    "prop_german_armored_car_piece1.png",
    "prop_german_armored_car_piece2.png",
    "prop_german_armored_car_piece3.png",
    "prop_german_armored_car_tire.png",
    "prop_german_panzer_part_1.png",
    "prop_german_panzer_part_2.png",
    "prop_german_panzer_part_3.png",
    "prop_haybale.png",
    "prop_helmet_german_africa.png",
    "prop_helmet_german_normandy.png",
    "prop_higgins_part1.png",
    "prop_higgins_part2.png",
    "prop_higgins_part3.png",
    "prop_higgins_part4.png",
    "prop_hotel_sign.png",
    "prop_hydrant.png",
    "prop_ivycornersingle01.png",
    "prop_ivycornersingle02.png",
    "prop_ivyedgebottom01.png",
    "prop_ivyedgehorizontal01.png",
    "prop_ivyedgehorizontal02.png",
    "prop_ivyedgeverticle01.png",
    "prop_ivysmallclump01.png",
    "prop_ivysmallclump02.png",
    "prop_ivysmallclump03.png",
    "prop_ivysmallverticle01.png",
    "prop_ivywindowcornertop01.png",
    "prop_ivy_bottom_1.png",
    "prop_ivy_corner_1.png",
    "prop_ivy_corner_2.png",
    "prop_kitchencopperpan.png",
    "prop_kitchenmetalpan.png",
    "prop_kitchenmetalpot.png",
    "prop_kitchenmetalpotlid.png",
    "prop_kitchen_faucet01.png",
    "prop_kitchen_sink01.png",
    "prop_kitchen_winebottle.png",
    "prop_ladder_wood_14_ft.png",
    "prop_ladder_wood_14_ft_static.png",
    "prop_ladder_wood_16_ft.png",
    "prop_ladder_wood_16_ft_static.png",
    "prop_lamp01.png",
    "prop_lamp01_on.png",
    "prop_lightbulbwire.png",
    "prop_lightbulbwirebase.png",
    "prop_lightbulb_off.png",
    "prop_lightbulb_on.png",
    "prop_lightpost.png",
    "prop_magazine1.png",
    "prop_magazine2.png",
    "prop_map_1.png",
    "prop_map_1_obj.png",
    "prop_map_2.png",
    "prop_map_2_obj.png",
    "prop_map_3.png",
    "prop_map_3_obj.png",
    "prop_map_4.png",
    "prop_map_4_obj.png",
    "prop_map_board.png",
    "prop_map_case_1.png",
    "prop_map_case_1_obj.png",
    "prop_map_case_2.png",
    "prop_map_case_2_obj.png",
    "prop_map_northafrica.png",
    "prop_map_northafrica_obj.png",
    "prop_market_stands1.png",
    "prop_market_stands2.png",
    "prop_market_stands3.png",
    "prop_market_stands4.png",
    "prop_market_stands5.png",
    "prop_market_stands6.png",
    "prop_market_stands7.png",
    "prop_market_stands8.png",
    "prop_metal_pail1.png",
    "prop_metal_pail2.png",
    "prop_metal_pail3.png",
    "prop_moroccanchainlamp_unlit.png",
    "prop_moroccan_chain.png",
    "prop_moroccan_chainlamp.png",
    "prop_mortar.png",
    "prop_mortar_ammunition.png",
    "prop_mortar_case.png",
    "prop_mortar_case2.png",
    "prop_mortar_crate.png",
    "prop_mortar_crate2.png",
    "prop_mortar_static.png",
    "prop_northafricawoodscreendouble.png",
    "prop_northafricawoodscreensingle.png",
    "prop_northafrica_oil_lamp.png",
    "prop_pictureframe01.png",
    "prop_pictureframe02.png",
    "prop_pillow1.png",
    "prop_pillow2.png",
    "prop_pillow3.png",
    "prop_pillow_duhoc1.png",
    "prop_pillow_duhoc2.png",
    "prop_pipetower_angleiron.png",
    "prop_pipetower_crossbar.png",
    "prop_pipetower_crossbarbrace.png",
    "prop_pipetower_crossbarcorner.png",
    "prop_pipetower_crossbarcorner2.png",
    "prop_pistol_shell.png",
    "prop_potato_crate.png",
    "prop_potbelly_stove.png",
    "prop_railswitch.png",
    "prop_rail_fuelcar.png",
    "prop_rail_graincar.png",
    "prop_rattanbasket1.png",
    "prop_rattanbasket2.png",
    "prop_rattanbasket3.png",
    "prop_rattanbasket4.png",
    "prop_rattanbasket5.png",
    "prop_rattanbasket6.png",
    "prop_rattanbasket7.png",
    "prop_rattanbasket8.png",
    "prop_redbrickpile_corner_in_debris_01.png",
    "prop_redbrickpile_corner_in_debris_02.png",
    "prop_redbrickpile_corner_out_debris_01.png",
    "prop_redbrickpile_corner_out_debris_02.png",
    "prop_redbrickpile_debris_01.png",
    "prop_redbrickpile_debris_02.png",
    "prop_redbrick_debris_01.png",
    "prop_redbrick_debris_02.png",
    "prop_redbrick_debris_03.png",
    "prop_redbrick_debris_04.png",
    "prop_redbrick_wall_debris_01.png",
    "prop_redbrick_wall_debris_02.png",
    "prop_redbrick_wall_debris_03.png",
    "prop_rifle_shell.png",
    "prop_rock.png",
    "prop_rubble_bar_big_01.png",
    "prop_rubble_bar_big_02.png",
    "prop_rubble_bar_big_03.png",
    "prop_rubble_bar_big_04.png",
    "prop_rubble_bar_sm_01.png",
    "prop_rubble_bar_sm_02.png",
    "prop_rubble_bar_sm_03.png",
    "prop_rubble_bar_sm_04.png",
    "prop_rubble_rock_01.png",
    "prop_rubble_rock_02.png",
    "prop_rubble_rock_03.png",
    "prop_rubble_rock_04.png",
    "prop_signallight.png",
    "prop_stoplight.png",
    "prop_stove01.png",
    "prop_stove01b.png",
    "prop_stove01c.png",
    "prop_stove02.png",
    "prop_stove02b.png",
    "prop_stove02c.png",
    "prop_streetlamp_dim.png",
    "prop_streetlamp_off.png",
    "prop_streetlamp_on.png",
    "prop_stuka_bomb.png",
    "prop_tiger_part_1.png",
    "prop_tiger_part_2.png",
    "prop_tiger_part_3.png",
    "prop_tinbox_oval_flat.png",
    "prop_tinbox_oval_tall.png",
    "prop_tinbox_rectangularflat01.png",
    "prop_tinbox_rectangularflat02.png",
    "prop_tinbox_rectangularflat03.png",
    "prop_tinbox_rectangulartall.png",
    "prop_tinbox_round_flat.png",
    "prop_tinbox_square_small.png",
    "prop_tinbox_square_tall01.png",
    "prop_tinbox_square_tall02.png",
    "prop_tincan.png",
    "prop_tombstone1.png",
    "prop_tombstone10.png",
    "prop_tombstone11.png",
    "prop_tombstone2.png",
    "prop_tombstone3.png",
    "prop_tombstone4.png",
    "prop_tombstone5.png",
    "prop_tombstone6.png",
    "prop_tombstone7.png",
    "prop_tombstone8.png",
    "prop_tombstone9.png",
    "prop_toujane_canopy.png",
    "prop_toujane_roadrock1.png",
    "prop_toujane_roadrock10.png",
    "prop_toujane_roadrock11.png",
    "prop_toujane_roadrock12.png",
    "prop_toujane_roadrock2.png",
    "prop_toujane_roadrock3.png",
    "prop_toujane_roadrock4.png",
    "prop_toujane_roadrock5.png",
    "prop_toujane_roadrock6.png",
    "prop_toujane_roadrock7.png",
    "prop_toujane_roadrock8.png",
    "prop_toujane_roadrock9.png",
    "prop_tractor.png",
    "prop_traincar01.png",
    "prop_traincar01_opendoor.png",
    "prop_traincar01_opendoor_snow.png",
    "prop_traincar01_snow.png",
    "prop_traincar_flat.png",
    "prop_traincar_flatfullbox.png",
    "prop_traincar_flatfullbox_snow.png",
    "prop_traincar_flathalfbox.png",
    "prop_traincar_flathalfbox_snow.png",
    "prop_traincar_flat_snow.png",
    "prop_trainwheels01.png",
    "prop_trainwheels01_snow.png",
    "prop_trenchgun_shell.png",
    "prop_trolleypole1.png",
    "prop_trolleypole2.png",
    "prop_trolleypole_side.png",
    "prop_trollycar_d.png",
    "prop_vehicle_crusader2_part1.png",
    "prop_vehicle_crusader2_part2.png",
    "prop_vehicle_crusader2_part3.png",
    "prop_vehicle_crusader2_part4.png",
    "prop_vine01.png",
    "prop_vinecorner01.png",
    "prop_vinecorner02.png",
    "prop_wickerbasket1.png",
    "prop_wickerbasket2.png",
    "prop_wickerbasket3.png",
    "prop_wickerbasket4.png",
    "prop_wickerbasket5.png",
    "prop_wickerbasket6.png",
    "prop_wickerbasket7.png",
    "prop_wickerbasket8.png",
    "prop_winebottle_breakable.png",
    "prop_winebottle_broken_bot.png",
    "prop_winebottle_broken_top.png",
    "prop_wine_crate.png",
    "prop_wooden_barrel1.png",
    "prop_woodstack1.png",
    "prop_wood_debris_big_burnt_01.png",
    "prop_wood_debris_big_burnt_01_noaicol.png",
    "prop_wood_debris_big_burnt_02.png",
    "prop_wood_debris_big_burnt_03.png",
    "prop_wood_debris_small_burnt_01.png",
    "prop_wood_debris_small_burnt_02.png",
    "prop_wood_debris_small_burnt_03.png",
    "prop_wood_splinter01.png",
    "prop_wood_splinter02.png",
    "railpipe01.png",
    "railpipe02.png",
    "railpipe03.png",
    "railpipe04.png",
    "railpipe05.png",
    "railpipe06.png",
    "railpipe07.png",
    "railpipe_bolts.png",
    "railpipe_connector.png",
    "railpipe_d01.png",
    "railpipe_d02.png",
    "railpipe_d03.png",
    "railpipe_s01.png",
    "railpipe_s02.png",
    "railpipe_s03.png",
    "railpipe_s06.png",
    "railpipe_sd01.png",
    "railpipe_sd02.png",
    "railpipe_sd03.png",
    "railsign01.png",
    "railsign02.png",
    "railsign03.png",
    "railtie01.png",
    "railtie02.png",
    "railtie03.png",
    "railtie04.png",
    "railtie05.png",
    "rock_egypt_a.png",
    "rock_egypt_a_night.png",
    "rock_egypt_b.png",
    "rock_egypt_b_night.png",
    "rock_egypt_c.png",
    "rock_egypt_c_night.png",
    "rock_egypt_d.png",
    "rock_egypt_d_night.png",
    "shadow_caen_hedge_wall_1.png",
    "shadow_caen_hedge_wall_2.png",
    "shadow_caen_hedge_wall_3.png",
    "shadow_caen_hedge_wall_group_1.png",
    "shadow_caen_spikeybush_01.png",
    "shadow_prop_moroccan_chainlamp.png",
    "shadow_tree_grey_oak_lg_a.png",
    "shadow_tree_grey_oak_med_a.png",
    "shadow_tree_grey_oak_xl_a.png",
    "shadow_tree_river_birch_lg_a.png",
    "sign_minefield1.png",
    "sign_minefield1_snow.png",
    "sign_minefield2.png",
    "sign_minefield2_snow.png",
    "sign_minefield3.png",
    "sign_minefield3_snow.png",
    "sign_minefieldclear.png",
    "sign_minefieldclear_snow.png",
    "sign_minefieldfake1.png",
    "sign_minefieldfake1_snow.png",
    "sign_minefieldfake2.png",
    "sign_minefieldfake2_snow.png",
    "sign_minefieldpath.png",
    "sign_minefieldpath_snow.png",
    "silo01.png",
    "silo01_pieces.png",
    "silo02.png",
    "silo03.png",
    "static_vehicle_german_kubelwagen.png",
    "stonewell.png",
    "storage_tank01.png",
    "sundirection_arrow.png",
    "tag_origin.png",
    "temp.png",
    "tree_desertbushy.png",
    "tree_desertpalm01.png",
    "tree_desertpalm02.png",
    "tree_desertpalm03.png",
    "tree_desertpalmfrond.png",
    "tree_desertpalmgroup.png",
    "tree_destoyed_snow_trunk_a.png",
    "tree_destoyed_snow_trunk_b.png",
    "tree_destoyed_trunk_a.png",
    "tree_destoyed_trunk_b.png",
    "tree_destroyed_fallen_log_a.png",
    "tree_destroyed_fallen_tree_a.png",
    "tree_destroyed_snow_fallen_log_a.png",
    "tree_destroyed_snow_fallen_tree_a.png",
    "tree_destroyed_snow_stump_a.png",
    "tree_destroyed_snow_stump_b.png",
    "tree_destroyed_snow_tree_a.png",
    "tree_destroyed_snow_tree_b.png",
    "tree_destroyed_stump_a.png",
    "tree_destroyed_stump_b.png",
    "tree_destroyed_tree_a.png",
    "tree_destroyed_tree_b.png",
    "tree_firhigh_piece1.png",
    "tree_firhigh_piece2.png",
    "tree_firhigh_piece3.png",
    "tree_grey_oak_lg_a.png",
    "tree_grey_oak_med_a.png",
    "tree_grey_oak_sm_a.png",
    "tree_grey_oak_xl_a.png",
    "tree_pine_lg_b.png",
    "tree_pine_sm_b.png",
    "tree_pine_xl_b.png",
    "tree_river_birch_lg_a.png",
    "tree_river_birch_lg_b.png",
    "tree_river_birch_med_a.png",
    "tree_river_birch_med_b.png",
    "tree_river_birch_xl_a.png",
    "tree_river_birch_xl_b.png",
    "tree_snow_pine_lg_c.png",
    "tree_snow_pine_sm_c.png",
    "tree_snow_pine_xl_c.png",
    "tree_snow_river_birch_lg_c.png",
    "tree_snow_river_birch_med_c.png",
    "tree_snow_river_birch_xl_c.png",
    "trenchframe01.png",
    "trenchframe01_broken.png",
    "trenchframe02.png",
    "trenchframe03.png",
    "trenchframe_piece01.png",
    "trenchframe_piece02.png",
    "tunisia_mountains.png",
    "tunisia_mountains_red.png",
    "us_ranger_radio_back.png",
    "us_ranger_radio_hand.png",
    "vehicle_africa_jeep.png",
    "vehicle_africa_jeep_can.png",
    "vehicle_africa_jeep_can_dmg.png",
    "vehicle_africa_jeep_can_static.png",
    "vehicle_africa_jeep_cot.png",
    "vehicle_africa_jeep_cot_dmg.png",
    "vehicle_africa_jeep_crash.png",
    "vehicle_africa_jeep_crash_static.png",
    "vehicle_africa_jeep_dmg.png",
    "vehicle_africa_jeep_static.png",
    "vehicle_american_jeep.png",
    "vehicle_american_jeep_can.png",
    "vehicle_american_jeep_can_damage.png",
    "vehicle_american_jeep_cot.png",
    "vehicle_american_jeep_cot_damage.png",
    "vehicle_american_jeep_crash_static.png",
    "vehicle_american_jeep_damage.png",
    "vehicle_american_sherman.png",
    "vehicle_american_sherman_d.png",
    "vehicle_american_sherman_desert.png",
    "vehicle_american_sherman_desert_d.png",
    "vehicle_american_sherman_static.png",
    "vehicle_cargoship.png",
    "vehicle_cargoship_crates.png",
    "vehicle_cargoship_crates_d.png",
    "vehicle_cargoship_d.png",
    "vehicle_civilian_car_d.png",
    "vehicle_civilian_car_red_d.png",
    "vehicle_civilian_car_white_d.png",
    "vehicle_condor.png",
    "vehicle_crusader2.png",
    "vehicle_crusader2_bitgobbler.png",
    "vehicle_crusader2_destroyed.png",
    "vehicle_crusader2_d_static.png",
    "vehicle_crusader2_static.png",
    "vehicle_crusader2_viewmodel.png",
    "vehicle_crusader2_viewmodel_bitgobbler.png",
    "vehicle_german_armored_car.png",
    "vehicle_german_armored_car_d.png",
    "vehicle_german_armored_car_d_static.png",
    "vehicle_german_armored_car_static.png",
    "vehicle_german_armored_car_winter_d_static.png",
    "vehicle_german_flakpanzer.png",
    "vehicle_german_kubel.png",
    "vehicle_german_kubel_d.png",
    "vehicle_german_kubel_d_static.png",
    "vehicle_german_kubel_nomandy.png",
    "vehicle_german_kubel_nomandy_static.png",
    "vehicle_german_kubel_normandy_d.png",
    "vehicle_german_kubel_normandy_d_static.png",
    "vehicle_german_kubel_static.png",
    "vehicle_halftrack_mg_brush.png",
    "vehicle_halftrack_mg_brush_d.png",
    "vehicle_halftrack_mg_brush_d_static.png",
    "vehicle_halftrack_mg_brush_static.png",
    "vehicle_halftrack_mg_desert.png",
    "vehicle_halftrack_mg_desert_static.png",
    "vehicle_halftrack_mg_snow.png",
    "vehicle_halftrack_mg_snow_static.png",
    "vehicle_halftrack_mg_woodland.png",
    "vehicle_halftrack_mg_woodland_d.png",
    "vehicle_halftrack_mg_woodland_d_static.png",
    "vehicle_halftrack_mg_woodland_static.png",
    "vehicle_halftrack_rockets_shell.png",
    "vehicle_halftrack_rockets_shell_d.png",
    "vehicle_halftrack_rockets_snow.png",
    "vehicle_halftrack_rockets_snow_static.png",
    "vehicle_halftrack_rockets_woodland.png",
    "vehicle_halftrack_rockets_woodland_d.png",
    "vehicle_halftrack_rockets_woodland_d_stat.png",
    "vehicle_halftrack_rockets_woodland_static.png",
    "vehicle_higgins.png",
    "vehicle_higgins_destroyed.png",
    "vehicle_higgins_grapple_hook.png",
    "vehicle_higgins_grapple_rope_short_l.png",
    "vehicle_higgins_grapple_rope_short_r.png",
    "vehicle_higgins_mortors.png",
    "vehicle_higgins_mortors_destroyed.png",
    "vehicle_higgins_vm.png",
    "vehicle_ltv4_buffalo.png",
    "vehicle_ltv4_buffalo_d.png",
    "vehicle_ltv4_buffalo_d_static.png",
    "vehicle_ltv4_buffalo_static.png",
    "vehicle_opel_blitz_desert.png",
    "vehicle_opel_blitz_desert_d.png",
    "vehicle_opel_blitz_desert_d_static.png",
    "vehicle_opel_blitz_desert_static.png",
    "vehicle_opel_blitz_snow.png",
    "vehicle_opel_blitz_snow_static.png",
    "vehicle_opel_blitz_woodland.png",
    "vehicle_opel_blitz_woodland_d.png",
    "vehicle_opel_blitz_woodland_d_static.png",
    "vehicle_opel_blitz_woodland_static.png",
    "vehicle_p51_mustang.png",
    "vehicle_panzer_ii.png",
    "vehicle_panzer_ii_destroyed.png",
    "vehicle_panzer_ii_destroyed_static.png",
    "vehicle_panzer_ii_l_tread_d.png",
    "vehicle_panzer_ii_r_tread_d.png",
    "vehicle_panzer_ii_static.png",
    "vehicle_panzer_ii_winter.png",
    "vehicle_panzer_ii_winter_destroyed.png",
    "vehicle_panzer_ii_winter_destroyed_static.png",
    "vehicle_panzer_ii_winter_l_tread_d.png",
    "vehicle_panzer_ii_winter_r_tread_d.png",
    "vehicle_panzer_ii_winter_static.png",
    "vehicle_russia_jeep.png",
    "vehicle_russia_jeep_can.png",
    "vehicle_russia_jeep_can_dmg.png",
    "vehicle_russia_jeep_cot.png",
    "vehicle_russia_jeep_cot_dmg.png",
    "vehicle_russia_jeep_crash_static.png",
    "vehicle_russia_jeep_dmg.png",
    "vehicle_sherman__tank_machinegun.png",
    "vehicle_spitfire_flying.png",
    "vehicle_stuka_flying.png",
    "vehicle_tiger_lefttread_d.png",
    "vehicle_tiger_righttread_d.png",
    "vehicle_tiger_snow_d.png",
    "vehicle_tiger_snow_d_static.png",
    "vehicle_tiger_woodland.png",
    "vehicle_tiger_woodland_brush.png",
    "vehicle_tiger_woodland_brush_static.png",
    "vehicle_tiger_woodland_d.png",
    "vehicle_tiger_woodland_d_brush.png",
    "vehicle_tiger_woodland_d_brush_static.png",
    "vehicle_tiger_woodland_d_static.png",
    "vehicle_tiger_woodland_static.png",
    "vehicle_uni_carrier_blow_piece01.png",
    "vehicle_uni_carrier_blow_piece02.png",
    "vehicle_uni_carrier_blow_piece03.png",
    "vehicle_uni_carrier_blow_piece04.png",
    "vehicle_uni_carrier_blow_piece05.png",
    "vehicle_uni_carrier_blow_piece06.png",
    "vehicle_uni_carrier_blow_piece07.png",
    "vehicle_uni_carrier_blow_piece08.png",
    "vehicle_uni_carrier_blow_piece09.png",
    "vehicle_uni_carrier_blow_piece10.png",
    "vehicle_uni_carrier_blow_piece11.png",
    "vehicle_uni_carrier_blow_piece12.png",
    "vehicle_uni_carrier_blow_piece13.png",
    "vehicle_uni_carrier_burned_prop1.png",
    "vehicle_uni_carrier_burned_prop2.png",
    "vehicle_uni_carrier_burned_prop3.png",
    "vehicle_uni_carrier_gr.png",
    "vehicle_uni_carrier_gr_destroyed.png",
    "vehicle_uni_carrier_gr_mud.png",
    "vehicle_uni_carrier_gr_mud_static.png",
    "vehicle_uni_carrier_gr_static.png",
    "vehicle_uni_carrier_ye_destroyed.png",
    "vehicle_uni_carrier_yw.png",
    "vehicle_uni_carrier_yw_dirt.png",
    "vehicle_uni_carrier_yw_dirt_static.png",
    "vehicle_uni_carrier_yw_static.png",
    "viewmodel_30cal.png",
    "viewmodel_bar.png",
    "viewmodel_binoculars.png",
    "viewmodel_bren.png",
    "viewmodel_britsmokegrenade.png",
    "viewmodel_carbine.png",
    "viewmodel_colt45.png",
    "viewmodel_default.png",
    "viewmodel_enfield.png",
    "viewmodel_enfield_scope.png",
    "viewmodel_g43.png",
    "viewmodel_g43_sniper.png",
    "viewmodel_germangrenade.png",
    "viewmodel_greasegun.png",
    "viewmodel_hands.png",
    "viewmodel_hands_british.png",
    "viewmodel_hands_british_bare.png",
    "viewmodel_hands_british_wet.png",
    "viewmodel_hands_cloth.png",
    "viewmodel_hands_german.png",
    "viewmodel_hands_german_afrika.png",
    "viewmodel_hands_german_winter.png",
    "viewmodel_hands_russian.png",
    "viewmodel_kar98k.png",
    "viewmodel_kar98_scope.png",
    "viewmodel_luger.png",
    "viewmodel_m1garand.png",
    "viewmodel_mg42.png",
    "viewmodel_mg42_new.png",
    "viewmodel_mk1.png",
    "viewmodel_mk2.png",
    "viewmodel_mosinnagant.png",
    "viewmodel_mosinnagant_cloth.png",
    "viewmodel_mp40.png",
    "viewmodel_mp44.png",
    "viewmodel_panzerschreck.png",
    "viewmodel_potato.png",
    "viewmodel_pps43.png",
    "viewmodel_ppsh.png",
    "viewmodel_russiangrenade.png",
    "viewmodel_springfield.png",
    "viewmodel_sten.png",
    "viewmodel_svt40.png",
    "viewmodel_thompson.png",
    "viewmodel_tokarev.png",
    "viewmodel_trenchgun.png",
    "viewmodel_ussmokegrenade.png",
    "viewmodel_webley.png",
    "void.png",
    "wall_tank_broke.png",
    "wall_tank_pieces.png",
    "wall_tank_whole.png",
    "waterpipe_spout.png",
    "weapon_30cal.png",
    "weapon_30cal_carry.png",
    "weapon_bar.png",
    "weapon_bren.png",
    "weapon_brit_smoke_grenade.png",
    "weapon_colt45.png",
    "weapon_enfield.png",
    "weapon_enfield_scope.png",
    "weapon_g43.png",
    "weapon_g43_scoped.png",
    "weapon_greasegun.png",
    "weapon_hcsmokegrenade.png",
    "weapon_kar98.png",
    "weapon_kar98_scoped.png",
    "weapon_kar98_scoped_obj.png",
    "weapon_luger.png",
    "weapon_m1carbine.png",
    "weapon_m1garand.png",
    "weapon_machinegun_crusader2.png",
    "weapon_machinegun_panzer2.png",
    "weapon_machinegun_tiger.png",
    "weapon_mg42.png",
    "weapon_mg42_carry.png",
    "weapon_miniturret_crusader2.png",
    "weapon_mk1grenade.png",
    "weapon_mk2fraggrenade.png",
    "weapon_mosinnagant.png",
    "weapon_mosinnagantscoped_cloth.png",
    "weapon_mosinnagantscoped_cloth_obj.png",
    "weapon_mosinnagant_obj.png",
    "weapon_mp40.png",
    "weapon_mp44.png",
    "weapon_nb39_smokegrenade.png",
    "weapon_nebelhandgrenate.png",
    "weapon_panzerfaust.png",
    "weapon_panzerfaust_empty.png",
    "weapon_panzerfaust_rocket.png",
    "weapon_panzerschreck.png",
    "weapon_panzerschreck_obj.png",
    "weapon_potato.png",
    "weapon_pps43.png",
    "weapon_ppsh.png",
    "weapon_russian_handgrenade.png",
    "weapon_springfield.png",
    "weapon_sten.png",
    "weapon_stickybomb.png",
    "weapon_stickybomb_obj.png",
    "weapon_svt40.png",
    "weapon_temp_fg42.png",
    "weapon_temp_histandardhd.png",
    "weapon_temp_m3greasegun.png",
    "weapon_temp_panzerfaust.png",
    "weapon_temp_panzershreck_rocket.png",
    "weapon_thompson.png",
    "weapon_trenchgun.png",
    "weapon_tt30.png",
    "weapon_tt30_obj.png",
    "weapon_us_smoke_grenade.png",
    "weapon_us_smoke_grenade_burnt.png",
    "weapon_us_smoke_grenade_obj.png",
    "weapon_us_thermite_grenade.png",
    "weapon_us_thermite_grenade_obj.png",
    "weapon_webley.png",
    "window_black.png",
    "window_black_a.png",
    "window_white_a.png",
    "window_white_b.png",
    "window_white_c.png",
    "window_white_d.png",
    "woodenpole_d.png"
]

SUGGESTED_FILTERS = [

    {"name": "Vehicles", "query": "vehicle_"},
    {"name": "Weapons", "query": "weapon_"},
    {"name": "Props", "query": "prop_"},
    {"name": "Furniture", "query": "furniture_"},
    {"name": "Military", "query": "military_"},
    {"name": "Brushes/Foliage", "query": "brush_"},
    {"name": "Sandbags", "query": "sandbag"},
    {"name": "Desert/Egypt", "query": "egypt"},
    {"name": "Snow/Winter", "query": "snow"},
    {"name": "Destroyed/Damaged", "query": "_d"},
    {"name": "Bunker", "query": "bunker"},
    {"name": "Awning", "query": "awning"}
]


DOWNLOAD_URL = "https://github.com/Grimm1/cod2xmodelimages/archive/refs/heads/main.zip"
INNER_FOLDER_NAME = "cod2xmodelimages-main"

class ModelViewerTab(ttk.Frame):
    def __init__(self, parent):
        super().__init__(parent)
        self.models = sorted(MODELS)
        self.filtered = self.models[:]
        self.current_filter = ""
        self.page = 1
        self.per_page = 30
        self.thumb_cache = {}
        self.current_full = None

        self.script_dir = Path(__file__).parent.parent
        self.thumb_dir = self.script_dir / "thumbnails"
        self.xmodel_dir = self.script_dir / "xmodel"

        self.images_ready = self.check_images_ready()

        self.create_widgets()

        if self.images_ready:
            self.render_page()

    def check_images_ready(self):
        if not self.thumb_dir.exists() or not self.xmodel_dir.exists():
            return False
        thumb_count = len(list(self.thumb_dir.glob("*.png")))
        xmodel_count = len(list(self.xmodel_dir.glob("*.png")))
        return thumb_count > 100 and xmodel_count > 100

    def create_widgets(self):
        main_container = ttk.Frame(self)
        main_container.pack(fill="both", expand=True)

        # LEFT PANEL – fixed 800px
        left = ttk.Frame(main_container, width=900)
        left.pack(side="left", fill="y")
        left.pack_propagate(False)

        if self.images_ready:
            self.build_normal_ui(left)
        else:
            self.build_setup_ui(left)

        # RIGHT PANEL
        right = ttk.Frame(main_container, padding=40)
        right.pack(side="left", fill="both", expand=True)

        preview_container = ttk.Frame(right)
        preview_container.pack(fill="both", expand=True)

        top_bar = ttk.Frame(preview_container)
        top_bar.pack(fill="x", pady=(0, 30))

        self.copy_btn = ttk.Button(top_bar, text="Copy Filename", command=self.copy_filename, width=40)
        self.copy_btn.pack(side="left")

        self.status_label = ttk.Label(top_bar, text="", foreground="#7ecfff", font=("Segoe UI", 11))
        self.status_label.pack(side="left", padx=30)

        self.full_label = ttk.Label(preview_container, background="#f0f0f0", anchor="center", justify="center")
        self.full_label.pack(fill="both", expand=True)

        if self.images_ready:
            self.full_label.config(
                text="Select a model thumbnail on the left\nto view the full-size preview here",
                foreground="#888",
                font=("Segoe UI", 16),
                justify="center"
            )
        else:
            self.full_label.config(
                text="Model images not installed yet.\nDownload them from the left panel to enable previews.",
                foreground="#888",
                font=("Segoe UI", 16),
                justify="center"
            )

# ui/tab_model_viewer.py — UPDATED build_normal_ui METHOD (with full horizontal + vertical scrolling)

    def build_normal_ui(self, parent):
        # Search
        self.search_var = tk.StringVar()
        search = ttk.Entry(parent, textvariable=self.search_var, font=("Segoe UI", 14))
        search.pack(fill="x", padx=30, pady=(30, 15))
        search.bind("<KeyRelease>", lambda e: self.apply_filters())

        # Filters
        filters_frame = ttk.Frame(parent)
        filters_frame.pack(fill="x", padx=30, pady=(0, 20))
        self.filter_buttons = {}
        self.filter_col = 0
        self.filter_row = 0
        self.add_filter_button(filters_frame, "All", "")

        for f in SUGGESTED_FILTERS:
            self.add_filter_button(filters_frame, f["name"], f["query"])

        # Pagination
        pag_frame = ttk.Frame(parent)
        pag_frame.pack(fill="x", padx=30, pady=(0, 10))
        ttk.Button(pag_frame, text="Previous", command=self.prev_page).pack(side="left")
        self.page_label = ttk.Label(pag_frame, text="", foreground="#ccc", font=("Segoe UI", 11))
        self.page_label.pack(side="left", padx=50)
        ttk.Button(pag_frame, text="Next", command=self.next_page).pack(side="left")

        # ── FIXED SCROLLABLE THUMBNAIL GRID (full height/width scrollbars, no truncation) ──
        thumb_container = ttk.Frame(parent)
        thumb_container.pack(fill="both", expand=True, padx=30, pady=10)

        # Grid config for proper scrollbar spanning
        thumb_container.grid_rowconfigure(0, weight=1)
        thumb_container.grid_columnconfigure(0, weight=1)

        thumb_canvas = tk.Canvas(thumb_container, background="#1e1e1e")
        thumb_v_scroll = tk.Scrollbar(thumb_container, orient="vertical", command=thumb_canvas.yview,
                                    width=24, bg="#666666", troughcolor="#1e1e1e",
                                    activebackground="#888888")
        thumb_h_scroll = tk.Scrollbar(thumb_container, orient="horizontal", command=thumb_canvas.xview,
                                    width=24, bg="#666666", troughcolor="#1e1e1e",
                                    activebackground="#888888")

        # Grid placement — full spanning with corner handling
        thumb_canvas.grid(row=0, column=0, sticky="nsew")
        thumb_v_scroll.grid(row=0, column=1, sticky="ns")
        thumb_h_scroll.grid(row=1, column=0, sticky="ew")

        thumb_canvas.configure(yscrollcommand=thumb_v_scroll.set, xscrollcommand=thumb_h_scroll.set)

        self.grid_frame = ttk.Frame(thumb_canvas)
        self.grid_frame.bind("<Configure>", lambda e: thumb_canvas.configure(scrollregion=thumb_canvas.bbox("all")))
        thumb_canvas.create_window((0, 0), window=self.grid_frame, anchor="nw")

        # Mouse wheel bindings
        def _on_mousewheel(event):
            thumb_canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

        def _on_shift_mousewheel(event):
            thumb_canvas.xview_scroll(int(-1 * (event.delta / 120)), "units")

        thumb_canvas.bind("<MouseWheel>", _on_mousewheel)
        thumb_canvas.bind("<Shift-MouseWheel>", _on_shift_mousewheel)

        # Linux support
        thumb_canvas.bind("<Button-4>", lambda e: thumb_canvas.yview_scroll(-1, "units"))
        thumb_canvas.bind("<Button-5>", lambda e: thumb_canvas.yview_scroll(1, "units"))
        thumb_canvas.bind("<Shift-Button-4>", lambda e: thumb_canvas.xview_scroll(-1, "units"))
        thumb_canvas.bind("<Shift-Button-5>", lambda e: thumb_canvas.xview_scroll(1, "units"))

        # Grid columns for thumbnails (3 columns, equal width)
        for c in range(3):
            self.grid_frame.grid_columnconfigure(c, weight=1, uniform="col")

    def add_filter_button(self, parent, text, query):
        btn = ttk.Button(parent, text=text, command=lambda q=query: self.set_filter(q))
        btn.grid(row=self.filter_row, column=self.filter_col, padx=4, pady=4, sticky="w")
        self.filter_buttons[query] = btn
        self.filter_col += 1
        if self.filter_col > 5:
            self.filter_col = 0
            self.filter_row += 1

    def download_images(self):
        if not messagebox.askyesno("Download Images", "Download the model images ZIP?\nThis is ~500-600MB and may take a few minutes."):
            return

        # Disable button and show progress
        for widget in self.winfo_children()[0].winfo_children()[0].winfo_children():
            if isinstance(widget, ttk.Button):
                widget.config(state="disabled")
            widget.destroy() if not isinstance(widget, ttk.Label) else widget.config(text="Downloading... Please wait.\nThis may take several minutes.")

        progress_label = ttk.Label(self.winfo_children()[0].winfo_children()[0], text="Downloading ZIP...", font=("Segoe UI", 12), foreground="#7ecfff")
        progress_label.pack(expand=True)

        self.update_idletasks()

        try:
            temp_dir = tempfile.mkdtemp()
            zip_path = Path(temp_dir) / "cod2images.zip"

            progress_label.config(text="Downloading ZIP file...")
            self.update_idletasks()
            urllib.request.urlretrieve(DOWNLOAD_URL, zip_path)

            progress_label.config(text="Extracting ZIP...")
            self.update_idletasks()
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)

            inner_path = Path(temp_dir) / INNER_FOLDER_NAME
            if not inner_path.exists():
                raise Exception("Unexpected ZIP structure")

            progress_label.config(text="Installing folders...")
            self.update_idletasks()

            for folder in ["thumbnails", "xmodel"]:
                src = inner_path / folder
                dst = self.script_dir / folder
                if dst.exists():
                    shutil.rmtree(dst)
                shutil.copytree(src, dst)

            shutil.rmtree(temp_dir)

            messagebox.showinfo("Success", "Images downloaded and installed successfully!\n\nPlease restart the application to use the model viewer.")

        except Exception as e:
            messagebox.showerror("Download Failed", f"An error occurred:\n{str(e)}\n\nYou can try again or download manually from GitHub.")
            # Rebuild setup UI on error
            for widget in self.winfo_children()[0].winfo_children()[0].winfo_children():
                widget.destroy()
            self.build_setup_ui(self.winfo_children()[0].winfo_children()[0])

    def set_filter(self, query):
        self.current_filter = query
        self.search_var.set(query if query else "")
        for q, b in self.filter_buttons.items():
            b.state(["pressed"] if q == query else ["!pressed"])
        self.apply_filters()

    def apply_filters(self):
        search = self.search_var.get().lower().strip()
        temp = self.models
        if self.current_filter:
            temp = [m for m in temp if self.current_filter.lower() in m.lower()]
        if search:
            temp = [m for m in temp if search in m.lower()]
        self.filtered = temp
        self.page = 1
        self.render_page()

    def render_page(self):
        for widget in self.grid_frame.winfo_children():
            widget.destroy()

        start = (self.page - 1) * self.per_page
        end = start + self.per_page
        page_items = self.filtered[start:end]

        for i, name in enumerate(page_items):
            row = i // 3
            col = i % 3

            frame = ttk.Frame(self.grid_frame, relief="ridge", borderwidth=2, padding=12)
            frame.grid(row=row, column=col, padx=12, pady=12, sticky="nsew")

            photo = self.get_thumbnail(name)
            img_label = ttk.Label(frame, image=photo, background="#f0f0f0")
            img_label.image = photo
            img_label.pack()

            name_label = ttk.Label(frame, text=name.replace(".png", ""), foreground="#ccc",
                                   background="#2d2d2d", font=("Segoe UI", 9), anchor="center")
            name_label.pack(pady=(12, 0))

            def on_enter(e, f=frame):
                f.config(borderwidth=4)
            def on_leave(e, f=frame):
                f.config(borderwidth=2)

            for w in (frame, img_label, name_label):
                w.bind("<Enter>", on_enter)
                w.bind("<Leave>", on_leave)
                w.bind("<Button-1>", lambda e, n=name: self.show_full(n))

        total_pages = max(1, (len(self.filtered) + self.per_page - 1) // self.per_page)
        self.page_label.config(text=f"Page {self.page} / {total_pages}  •  {len(self.filtered)} models total")

    def get_thumbnail(self, filename):
        if filename in self.thumb_cache:
            return self.thumb_cache[filename]

        path = self.thumb_dir / filename
        if path.exists():
            try:
                img = Image.open(path)
                img = img.resize((220, 220), Image.LANCZOS)
                photo = ImageTk.PhotoImage(img)
                self.thumb_cache[filename] = photo
                return photo
            except Exception as e:
                print(f"Thumb error {filename}: {e}")

        img = Image.new("RGB", (220, 220), "#333333")
        photo = ImageTk.PhotoImage(img)
        self.thumb_cache[filename] = photo
        return photo

    def show_full(self, filename):
        self.current_full = filename
        path = self.xmodel_dir / filename
        if path.exists():
            try:
                img = Image.open(path)
                img.thumbnail((1000, 1000), Image.LANCZOS)
                photo = ImageTk.PhotoImage(img)
                self.full_label.config(image=photo, text="")
                self.full_label.image = photo
                self.copy_btn.config(text=f"Copy: {filename.replace('.png', '')}")
            except Exception as e:
                print(f"Full error {filename}: {e}")
                self.full_label.config(image="", text="Error loading image", foreground="#ff6666")
        else:
            self.full_label.config(image="", text="Full image not found\n(xmodel folder)", foreground="#ff6666")

    def copy_filename(self):
        if not self.current_full:
            return
        name = self.current_full.replace(".png", "")
        self.clipboard_clear()
        self.clipboard_append(name)
        self.status_label.config(text="Copied!")
        self.after(1500, lambda: self.status_label.config(text=""))

    def prev_page(self):
        if self.page > 1:
            self.page -= 1
            self.render_page()

    def next_page(self):
        if self.page < (len(self.filtered) + self.per_page - 1) // self.per_page:
            self.page += 1
            self.render_page()